name: build

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 8 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build
        if: success()
        run: |
          platformio run -e ethernet-relay-temp-v1 -e ethernet-relay-temp-v1-debug
